app/urls.py
from django.urls import path
from . import views
from .views import ChartData

app_name = 'app'

urlpatterns = [
    path('', views.slotmachine, name='slotmachine'),
    # path('', views.SlotMachine.as_view(), name='slotmachine'),
    path('deposit/', views.deposit, name='deposit'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('yamadaslot/', views.Aboutview.as_view(), name='yamadaslot'),
    path("api/chart/data/", ChartData.as_view(), name="chartdata"),
]

authapp/urls.py
from django.urls import path
from . import views
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views


app_name = 'authapp'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login', views.Login.as_view(), name='login'),

    path('logout/', views.logout_view, name='logout'),
    # path('logout/', views.Logout.as_view(), name='logout'),
    # path('slot/', views.Top.as_view(), name='top'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

pro43_game5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authapp.urls', namespace='authapp')),
    path('slot/', include('app.urls', namespace='app')),
]

authapp/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.template.backends import django
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
from app.models import GraphHistory1, GraphHistory2, History


class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    total_game_number =models.PositiveIntegerField(default=0)
    total_medals =models.PositiveIntegerField(default=2000)
    turbo_slot1 = models.BooleanField(default=False, help_text="aaa")
    turbo_slot2 = models.BooleanField(default=False)
    # graph_history1_id = models.ForeignKey(GraphHistory1, verbose_name='slot_user', on_delete=models.PROTECT)
    # graph_history2_id = models.ForeignKey(GraphHistory2, verbose_name='slot_user', on_delete=models.PROTECT)
    # History_id = models.ForeignKey(History, verbose_name='slot_user', on_delete=models.PROTECT)


    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import get_user_model


User = get_user_model()


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email',)
        else:
            fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email', 'first_name', 'last_name')
        else:
            fields = ('username', 'email', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

authapp/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import Http404, HttpResponseBadRequest, request
from django.shortcuts import redirect, resolve_url
from django.template.loader import get_template
from django.views import generic
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from pro43_game5 import settings
from .forms import LoginForm, UserCreateForm, UserUpdateForm, MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm
from django.urls import reverse_lazy
from app.models import History
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect



User = get_user_model()


class Top(generic.TemplateView):
    template_name = 'authapp/top.html'


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'authapp/login.html'


# class Logout(LoginRequiredMixin, LogoutView):
#     """ログアウトページ"""
#     template_name = 'authapp/logged2_out.html'
@login_required
def logout_view(request):

    current_user = request.user
    player_account = User.objects.get(email=current_user).pk
    try:
        logout_medal1 = History.objects.filter(user = player_account, slot_number_id=1).values_list('medals', flat=True).order_by('-id')[0]
    except:
        logout_medal1 = 0
    try:
        logout_medal2 = History.objects.filter(user = player_account, slot_number_id=2).values_list('medals', flat=True).order_by('-id')[0]
    except:
        logout_medal2 = 0
    print(logout_medal1)

    if logout_medal1 == 0 and logout_medal2 == 0:
        logout(request)
        return render(request, "authapp/logged2_out.html")

    else:
        messages.info(request, 'your medal is remained in SLOT. please withdraw.')
        return redirect("/")




class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'authapp/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        #'token': dumps(user.pk),これで、分かりにくいアクティベーションurlが作れる。
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('authapp/mail_template/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('authapp/mail_template/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        return redirect('authapp:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'authapp/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'authapp/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60 * 60 * 24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoenNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'authapp/user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'authapp/user_form.html'

    def get_success_url(self):
        # messages.success(request, 'アップデートに成功しました。')
        return resolve_url('authapp:user_detail', pk=self.kwargs['pk'])


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('authapp:password_change_done')
    template_name = 'authapp/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'authapp/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'authapp/mail_template/reset/subject.txt'
    email_template_name = 'authapp/mail_template/reset/message.txt'
    template_name = 'authapp/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('authapp:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'authapp/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('register:password_reset_complete')
    template_name = 'authapp/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'authapp/password_reset_complete.html'



@login_required(login_url = "/login")
def dashboard(request):
    # get user_id
    current_user = request.user
    # print(current_user)
    player_account = User.objects.get(email=current_user).pk
    print(player_account)
    # get user_id and
    my_wallet1 =  User.objects.filter(email=current_user).values_list('total_medals', flat=True)[0]
    print(my_wallet1)
    my_total_games1 = User.objects.filter(email=current_user).values_list('total_game_number', flat=True)[0]
    print(my_total_games1)
    #initial Medal in SLOT1 medal window
    # current_user = request.user
    # player_account = User.objects.get(email=current_user).pk

    try:
        game_medal1 = History.objects.filter(user=player_account, slot_number_id=1).values_list('medals', flat=True).order_by('-id')[0]
    except:
        game_medal1 = 0

    try:
        game_count1 = History.objects.filter(user=player_account, slot_number_id=1).values_list('history', flat=True).order_by('-id')[0]
    except:
        game_count1 = 0

    try:
        game_medal2 = History.objects.filter(user=player_account, slot_number_id=2).values_list('medals', flat=True).order_by('-id')[0]
    except:
        game_medal2 = 0

    try:
        game_count2 = History.objects.filter(user=player_account, slot_number_id=2).values_list('history', flat=True).order_by('-id')[0]
    except:
        game_count2 = 0

    return render(request, 'app/game.html', {'section': 'dashboard',
                                                  'dashboard_medals': my_wallet1,
                                                  'total_games': my_total_games1,
                                                  'game_medal1': game_medal1,
                                                  'count': game_count1,
                                                  'dashboard_medals2': game_medal2,
                                                  'dashboard_count2': game_count2,
                                                  })

authapp/templates/authapp/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <link href="//fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
    <link href="{% static 'authapp/css/style.css' %}" rel="stylesheet" type="text/css">
{#    <link href="{% static 'app/css/game.css' %}" rel="stylesheet" type="text/css">#}

    <title>会員登録サンプル</title>
</head>
<style type="text/css">
        body {
         font-family: 'Press Start 2P', cursive;
         background: url('{% static "authapp/images/background2.png" %}') no-repeat center center fixed;
         -webkit-background-size: cover;
         -moz-background-size: cover;
         -o-background-size: cover;
         background-size: cover;
         display: flex;
        flex-direction: column;
        height: 100%;
        }
</style>

<body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
    {% if request.user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'app:slotmachine' %}"><img class="logo" src="{% static "authapp/images/logo.png" %}"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    {% else %}
          <a class="navbar-brand" href="{% url 'authapp:login' %}"><img class="logo" src="{% static "authapp/images/logo.png" %}"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    {% endif %}
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'authapp:user_detail' user.pk %}">UserInfo</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'authapp:user_update' user.pk %}">UpdateUserInfo</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'authapp:password_change' %}">ChangePassword</a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
          <li>
{#          <li class="nav-item">#}
            {% if request.user.is_authenticated %}
                <span class="nav-item nav-link pull-right" >{{ request.user.username }}</span>
            {% else %}
             {#             <a href="{% url 'authapp:user_create' %}" class="btn btn-success btn-lg btn-block" >会員登録</a>#}
             <a href="{% url 'authapp:user_create' %}" class="nav-item nav-link pull-right" >CreateAccount</a>
            {% endif %}

          </li>
{#          <li class="nav-item">#}
          <li>
            {% if request.user.is_authenticated %}
                <a href="{% url "authapp:logout" %}" class="nav-item nav-link pull-right">Logout</a>
            {% else %}
                <a href="{% url "authapp:login" %}" class="nav-item nav-link pull-right">Log-in</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>

    <!-- メインコンテント -->
    <div class="container mt-3 main-content">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"#}
{#            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"#}
{#            crossorigin="anonymous"></script>#}


</body>
    <footer class="footer">
        <div class="footer-copyright py-3 text-center bg-light mt-5">
            © 2018 Copyright:
            <a href=""> Micro Writing </a>
        </div>
    </footer>


</html>

authapp/templates/authapp/logged2_out.html
{% extends "authapp/base.html" %}

{% block title %}Logged out{% endblock %}

{% block content %}
<div class="container main-content mx-auto mt-5">
<div class="row main-slot">

        <h1>Logged out</h1>
        <p>You have been successfully logged out. You can <a href="{% url "authapp:login" %}">log-in again</a>.</p>
  </div>
</div>

{% endblock %}

authapp/templates/authapp/login.html
{% extends "authapp/base.html" %}
{#{% load bootstrap %}#}
{% load static %}

{% block title %}Log-in{% endblock %}
{% block content %}

<div class="container main-content mt-5">
    <div class="row main-slot">
    <div class="center-block  mx-auto login">
        <h1 class="text-center">Log-in</h1>
            <p>Please, use the following form to log-in:</p>
                <form action="" method="POST">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field }}
                        {{ field.errors }}
                        <hr>
                    {% endfor %}
                    <button type="submit" class="btn btn-success btn-block" >Login</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                    {% csrf_token %}
                </form>
    </div>
    </div>
</div>
{% endblock %}

authapp/templates/authapp/password_change.html
{% extends "authapp/base.html" %}
{% block content %}
    <div class="container main-content mt-5">
    <div class="row main-slot">
    <div class="center-block  mx-auto login">
        <form action="" method="POST">
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-block" >Update</button>
        </form>
    </div>
    </div>
    </div>
{% endblock %}

authapp/templates/authapp/password_change_done.html
{% extends "authapp/base.html" %}
{% block content %}
    <div class="container main-content mt-5">
    <div class="row main-slot">
    <div class="center-block  mx-auto login">
        <p>Successfully change the password.</p>
        <p><a class="btn btn-success btn-block" href="{% url 'authapp:dashboard' %}">Go back Game</a></p>
{#        <button type="submit" class="btn btn-success btn-block" >Update</button>#}
    </div>
    </div>
    </div>
{% endblock %}

authapp/templates/authapp/password_reset_confirm.html
{% extends "authapp/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

authapp/templates/authapp/password_reset_done.html
{% extends "authapp/base.html" %}
{% block content %}
<p>
    パスワード再設定用のメールを送信しました。<br>
    メールに記載されているリンクから再設定を行ってください。
</p>
{% endblock %}

authapp/templates/authapp/password_reset_form.html
{% extends "authapp/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

authapp/templates/authapp/top.html
{% extends "authapp/base.html" %}
{% block content %}
<p>ここに、好きな内容を入れる。</p>
{% endblock %}

authapp/templates/authapp/user_create.html
{% extends "authapp/base.html" %}
{% block content %}
    <div class="container main-content mt-5">
    <div class="row main-slot">
    <div class="center-block  mx-auto login">
    <h1 class="text-center">Registration</h1>

        <form action="" method="POST">
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-lg btn-block">送信</button>
        </form>

    </div>
    </div>
    </div>
{% endblock %}

authapp/templates/authapp/user_create_complete.html
{% extends "authapp/base.html" %}
{% block content %}
    <div class="container main-content mt-5">
    <div class="row main-slot">
    <div class="center-block  mx-auto login">
        <p>
            本登録が完了しました。<br>
            登録されたメールアドレスとパスワードでログインしてください。<br>
            <a class="btn btn-primary btn-lg" href="{% url 'authapp:login' %}">ログイン</a>
        </p>
    </div>
    </div>
    </div>
{% endblock %}